### ISSUE TITLE
8266可以嘛？大佬具体怎么使用那？

### ISSUE THREAD

**Issue by paterli** [JackHuang021/ld2410s#2]

**Comment by paterli** [comment]
用win 命令行编译报错了，麻烦大佬看看
ERROR Unable to import component binary_sensor:
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\site-packages\esphome\loader.py", line 169, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\1\Desktop\esphome\ld2410s\components\binary_sensor.py", line 10, in <module>
    from . import CONF_LD2410S_ID, LD2410SComponent
ImportError: cannot import name 'CONF_LD2410S_ID' from 'esphome.components' (C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\site-packages\esphome\components\__init__.py)
Failed config

binary_sensor: [source ./2410s.yaml:52]

  Component not found: binary_sensor.
